src/Pumukit/WebTVBundle/Controller/SearchController.php
Fixes #123
Note: I checked the Géant bundle just in case. These values are not being used in the overrided layout, so everything is alright:
Géant file: [Search/filtersmultimediaobjects.html.twig](
https://github.com/teltek/PuMuKIT2-geant-bundle/blob/master/Resources/views/Search/filtersmultimediaobjects.html.twig)
=> #123 WebTVBundle: Removed deprecated 'dates'

src/Pumukit/WebTVBundle/Resources/views/Widget/menu.html.twig, src/Pumukit/WebTVBundle/Resources/views/default.css.twig
This css was harmful for all 'a' elements in the menu, regardless of them being appropiate for being highlighted as elements.
* Rewrote css to use a class 'element' instead of the generic *a* block
=> #11152 WebTVBundle: Improved css selection.

src/Pumukit/SchemaBundle/Repository/SeriesRepository.php, src/Pumukit/SchemaBundle/Services/SeriesService.php, src/Pumukit/WizardBundle/Controller/DefaultController.php, src/Pumukit/WizardBundle/DependencyInjection/Configuration.php, src/Pumukit/WizardBundle/DependencyInjection/PumukitWizardExtension.php
Added parameter to chose this option:
```
pumukit_wizard:
reuse_series: true
reuse_admin_series: true
```
By default `reuse_admin_series` is set to false.
=> Wizard: show only series of admin in series step

src/Pumukit/InspectionBundle/Services/InspectionFfprobeService.php
In videos with no duration, ffprobe may not return any 'duration' property at all in the json. This check prevents that from causing an error 500
=> InspectionBundle: Defensive programming for 'duration'.

src/Pumukit/InspectionBundle/Services/InspectionFfprobeService.php
Some videos are missing enough metadata that this section throws an exception for having some of those values missing.
Since we are able to restore this files after they are uploaded, it is advisable to be defensive about it and let them transcode.
=> Inspection bundle: Defensive programing for other values returned by ffprobe

src/Pumukit/WebTVBundle/Resources/views/Index/403forbidden.html.twig, src/Pumukit/WebTVBundle/Resources/views/MultimediaObject/player.html.twig
* In Twig template of WebTVBundle MultimediaObjet player.html.twig it was being use the url() function instead of path()
* In Twig template of 403forbidden.html.twig the trans tag of `Log In` text was missing.
=> Bugfix 13176 http iframe

src/Pumukit/EncoderBundle/DependencyInjection/Configuration.php, src/Pumukit/EncoderBundle/Services/JobService.php
Adds an optional property to the encoders that, if set to true, skips the 'noduration' checks.
Useful if the profile is meant to reindex the files.
=> Feature 13182 duration 0 encoder

src/Pumukit/WizardBundle/Resources/views/pumukit2_wizard.js.twig
Follows this other pull request: #309 
After the unification of branches 2.3.x and 2.4.x in the issue #305 , the previous pull request is moved to 2.3.x branch.
The travis may fail because of commented console.log:
```
src/Pumukit/NewAdminBundle/Resources/views/MultimediaObject/acordeon.html.twig:105:
//console.log($(form).serialize());
```
=> TTK-13340 WizardBundle: add IE workaround for enctype

src/Pumukit/EncoderBundle/Services/JobService.php
There seems to be a typo.
In searchError, we check `$profile['nocheckduration']`, which would never exist if we don't pass the full `$profile`.
=> TTK-13182 Fixed wrong parameter passing.

app/SymfonyRequirements.php, composer.json, composer.lock, web/config.php
Symfony tip: Don’t use an empty PSR-4 prefix in your PHP applications. It hurts performance.
See:
* https://twitter.com/symfony_en/status/836232295329722370
* https://github.com/symfony/symfony-demo/pull/490
* https://github.com/symfony/symfony-standard/pull/1048/files
Also doing:
```
- Removing twig/twig (v1.30.0)
- Installing twig/twig (v1.32.0)
- Removing symfony/symfony (v2.8.15)
- Installing symfony/symfony (v2.8.17)
- Removing paragonie/random_compat (v2.0.4)
- Installing paragonie/random_compat (v2.0.7)
- Removing doctrine/dbal (v2.5.5)
- Installing doctrine/dbal (v2.5.12)
- Removing doctrine/doctrine-bundle (1.6.4)
- Installing doctrine/doctrine-bundle (1.6.7)
- Removing sensiolabs/security-checker (v4.0.0)
- Installing sensiolabs/security-checker (v4.0.1)
- Removing …
```
=> Improve autoload performances by default

src/Pumukit/WebTVBundle/Controller/MultimediaObjectController.php, src/Pumukit/WebTVBundle/Resources/views/MultimediaObject/player.html.twig
teltek/PuMuKIT2-paella-player-bundle@f28cde54
This change made possible to select one single track from an Opencast video. However, since the WebTVBundle would always set a track, this had the undesirable effect of ALWAYS should only one track.
=> Unset track to allow playing dual-stream after changes in commit:

src/Pumukit/WebTVBundle/Resources/views/MultimediaObject/player.html.twig
This change is required for https://github.com/teltek/PuMuKIT2-paella-player-bundle/pull/25 to work. Since it is generic, it may help with other future changes to the players.
Note: In: 
src/Pumukit/WebTVBundle/Resources/views/MultimediaObject/player.html.twig
line 17 I did:
```
{% set iframe_parameters = {'secret':multimediaObject.secret, 'autostart': autostart} | merge(app.request.query.all) %}
```
I would like to do instead:
```
{% set iframe_parameters = iframe_parameters | merge({'secret':multimediaObject.secret}) %}
```
but that would mean the magic url would also have the multimedia object id. Since that could interact with the annotations and I can't test it properly right now, I used the more conservative approach, but it would be nice to change it.
=> TTK-13965 WebTVBundle: Sent extra request parameters to player iframe

src/Pumukit/SchemaBundle/Services/GroupService.php
Fix `GroupService::delete` always check the origin.
Original state:
GroupService::update - not check origin
GroupService::delete - check origin always
UserService::update - check origin
UserService::delete - not check origin
UserService::addGroup - check origin
UserService::deleteGroup - check origin
=> TTK-13840 First step to fix user/group services API

src/Pumukit/Legacy/WebTVBundle/Resources/views/layout.html.twig, src/Pumukit/WebTVBundle/Resources/views/Layout/base.html.twig
This fixes the use of language attributes on the html element.
https://www.w3.org/TR/WCAG20-TECHS/H57.html
=> TTK-14607: A11Y - Fix H57 errors - lang attribute in html tag

src/Pumukit/NewAdminBundle/Resources/views/Series/list.html.twig, src/Pumukit/NewAdminBundle/Resources/views/pumukit2.css.twig
This fixes H43: Using id and headers attributes to associate data cells with header cells in data tables.
https://www.w3.org/TR/WCAG20-TECHS/H43.html
=> TTK-14615: A11Y - H43 - Change th to td in series list table foot

src/Pumukit/WebTVBundle/Resources/views/Widget/breadcrumbs.html.twig
Since the line:
`   var leftOffset = (.offset()[left]);`
gives an error, the rest of the code is not executed. This error is due to the id 'content' being removed on: d71fe7f67225a6776bc5cfda84efb9f93eb28272
If that is fixed, the current code creates an infinite while loop.
I have opted for removing the logic altogether.
As a note, the function it was a string shortener for when the breadcrumb title takes too much space, I believe.
=> Fixed javascript error:

src/Pumukit/PodcastBundle/Controller/FeedController.php
Non standard solution copied from ondacero:
http://www.ondacero.es/rss/podcast/8502/podcast.xml
=> TTK-14869 Add itunes:image tag into podcast item

src/Pumukit/SchemaBundle/Services/FactoryService.php, src/Pumukit/SchemaBundle/Services/TagService.php
There's an incident with the `flush` of the new MultimediaObjectListener,
This flush is executed before calling `setSeries`.
The failed test flow is:
```
FactoryService::cloneMultimediaObject
$new = new MultimediaObject();
setMetadata
setTags
TagService::addTag
$this->dispatcher->dispatchUpdate($mmobj);
MultimediaObjectListener::postUpdate
$this->dm->flush();
addGroups
setSeries
$this->dm->persist($new);
...
```
To fix the test and improve the performance, two changes are applied:
* In FactoryService move `setSeries` at the top of the method.
* In TagService only emit events if flush in the database.
=> TTK-15012 Fix FactoryServiceTest::testClone

src/Pumukit/EncoderBundle/Resources/views/Info/cpus.html.twig
Activate CPU fails if their name has a dot char.
```
$('#maintenance-pre_transco.pmk.es-toggle').click(...
```
=> TTK-15075 Fix activate CPU

src/Pumukit/OpencastBundle/Resources/views/MediaPackage/list.html.twig
`i18n.one.Series` vs `i18n.one.series`
Series is both a singular and a plural form. Series is not a good word
for an user interface. Collection and Set should be better.
=> TTK-15125 Fix typo with i18n.one.Series

src/Pumukit/WebTVBundle/Resources/views/Misc/series.html.twig
Renaming the section to 'subtitle' makes it equal to the mmobj template, so it's css is also applied here.
I found that better than to duplicate the css
**Note:** Merge upwards (2.3.x, ...)
=> TTK-15273 WebTVBundle: Fixed 'nowrap' for series subtitles

src/Pumukit/WebTVBundle/Resources/views/Misc/miniMultimediaObjects.html.twig, src/Pumukit/WebTVBundle/Resources/views/Search/list.html.twig
As far as I know, the "publicDate" is used to list series, while the "recordDate" is used for mmobjs,
this makes sense to me, so I corrected the wrong instances where a mmobj would be listed by their "publicDate"
Merge upwards.
=> TTK-15275 WebTVBundle: Replaced incorrect uses of "publicDate"

src/Pumukit/NewAdminBundle/Resources/views/Themes/fields.html.twig
Current behavior:
* Two languages:
* One language:
Change proposal:
* Two languages: No changes
* One language:
=> TTK-16670 No language info with only language

.pa11y.json, .travis.yml
$ pa11y -l error -s WCAG2AA -r cli http://localhost:8000/
Welcome to Pa11y
> Running Pa11y on URL http://localhost:8000/
Error: Failed to launch chrome!
[0222/125121.779468:FATAL:zygote_host_impl_linux.cc(124)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
#0 0x55addc0ef8ec base::debug::StackTrace::StackTrace()
#1 0x55addc107770 logging::LogMessage::~LogMessage()
#2 0x55addb1c1f61 content::ZygoteHostImpl::Init()
#3 0x55addae3c3b5 content::BrowserMainLoop::EarlyInitialization()
#4 0x55addae4230a content::BrowserMainRunnerImpl::Initialize()
#5 …
=> Fix travis (pa11y error)

src/Pumukit/CoreBundle/EventListener/AjaxSessionCloseListener.php, src/Pumukit/CoreBundle/Resources/config/services.xml, src/Pumukit/NewAdminBundle/Controller/AdminController.php, src/Pumukit/NewAdminBundle/Controller/MultimediaObjectController.php, src/Pumukit/NewAdminBundle/Controller/UNESCOController.php
By default only one request can execute synchronously per session at the
same time. Other requests for the same session will wait inside the
session_start() call until the previous requests are finished. This
commit fixes that multiple concurrent Ajax requests will wait for each other
and making the application much slower than it must be.
https://tideways.io/profiler/blog/slow-ajax-requests-in-your-symfony-application-apply-this-simple-fix
=> TTK-17299 Performance: Add AjaxSessionCloseListener

src/Pumukit/LiveBundle/Document/Live.php, src/Pumukit/SchemaBundle/Document/Broadcast.php, src/Pumukit/SchemaBundle/Document/EmbeddedBroadcast.php
Fixes:
> The `Symfony\Component\Validator\Constraints\True` class is deprecated since version 2.7 and will be removed in 3.0. Use the `IsTrue` class in the same namespace instead.
=> PHP7 Fix using True as class name as it is reserved

src/Pumukit/SchemaBundle/Document/MultimediaObject.php
```
[Symfony\Component\Debug\Exception\FatalErrorException]
Compile Error: Cannot use 'String' as class name as it is reserved
Compile Error: Cannot use 'Int' as class name as it is reserved
Compile Error: Cannot use 'Bool' as class name as it is reserved
...
```
See: https://github.com/doctrine/DoctrineMongoDBBundle/issues/351
Solution:
```
find src -name \*php -exec sed -i "s/MongoDB\\\String/MongoDB\\\Field(type=\"string\")/g" {} \;
find src -name \*php -exec sed -i "s/MongoDB\\\Int/MongoDB\\\Field(type=\"int\")/g" {} \;
find src -name \*php -exec sed -i "s/MongoDB\\\Boolean/MongoDB\\\Field(type=\"boolean\")/g" {} \;
find src -name \*php -exec sed -i "s/MongoDB\\\Bool/MongoDB\\\Field(type=\"boolean\")/g" {} \;
find src -name \*php -exec sed -i …
```
=> PHP7 Cannot use ODM annotations as class name as it is reserved (II)

src/Pumukit/NewAdminBundle/Controller/LegacyEventPicController.php, src/Pumukit/NewAdminBundle/Controller/MaterialController.php, src/Pumukit/NewAdminBundle/Controller/MultimediaObjectPicController.php, src/Pumukit/NewAdminBundle/Controller/PlaylistPicController.php, src/Pumukit/NewAdminBundle/Controller/SeriesPicController.php, src/Pumukit/NewAdminBundle/Controller/TrackController.php
From https://insight.sensiolabs.com/projects/2d795933-1d37-4624-bfb7-98acdffd4e0e/analyses/4896?status=violations#669300618
Joke: "PHP super globals should never be used" == "PHP should never be used"
=> TTK-19189 PHP super globals should never be used

src/Pumukit/WebTVBundle/Controller/MultimediaObjectController.php, src/Pumukit/WebTVBundle/Resources/views/MultimediaObject/index.html.twig
This PR adds info in WebTVBundle:MultimediaObject:seriesAction about the request coming from WebTVBundle:MultimediaObject:index.html.twig to discern about magic url.
=> TTK-18654: Fix info about series when rendering from video magic url

src/Pumukit/WebTVBundle/Controller/SecurityController.php
If the multimedia object is not published, this route always returns a 404.
This route should be consistent with the back-office, so I changed the filter from the WebTVController to the AdminController.
=> WebTVBundle: Edit button. Changed mmobj filter to AdminController

src/Pumukit/SchemaBundle/Command/NumericalIDCommand.php
Line   Pumukit/SchemaBundle/Command/NumericalIDCommand.php                      
------ ------------------------------------------------------------------------- 
109    Method                                                                   
Pumukit\SchemaBundle\Command\NumericalIDCommand::getMultimediaObjects()  
invoked with 3 parameters, 1-2 required.
=> Hotfix phpstan

src/Pumukit/WebTVBundle/Resources/views/Layout/base.html.twig
This solves two issues:
* We avoid having having to use the footer to add analytics
* Analytics appear on the back-office as well
=> TTK-20182 WebTVBundle: Added analytics template to base 

src/Pumukit/SchemaBundle/Services/PersonService.php
If false, the function won't dispatch the mmobj_update event
This helps optimize the code when having to call this function several times in a row,
as it stands now, each mmobj_update makes a mongo query to update the text index.
=> PersonService: Adds an optional 'dispatch' flag

.travis.yml
The command "php app/console lint:twig src" exited with 1.
>> Unknown "col_calculator" function.
>> Unknown "add_clear_fix_md" function.
...
=> Workaround to fix travis with FutureWebTVBundle

src/Pumukit/WorkflowBundle/EventListener/JobGeneratorListener.php, src/Pumukit/WorkflowBundle/Tests/EventListener/JobGeneratorListenerTest.php
Not generate a new job with video_h264 profile if the multimedia object already contains other with PUCHWEBTV
=> TTK-21375 Workflow: not generate new job for published video

src/Pumukit/OpencastBundle/Services/OpencastImportService.php
php -v
```
PHP 5.6.38 (cli) (built: Oct 24 2018 12:16:02) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```
php -a
```
Interactive shell
php > $string = 'its a string';
php > var_dump(isset($string[0]));
bool(true)
```
=> TTK-21759 use is_array instead of isset

src/Pumukit/NewAdminBundle/Resources/views/MultimediaObject/index.html.twig
I noticed that this title is not translated. It should be, it probably was an oversight.
=> TTK-21710 NewAdminBundle: Added 'trans' to button hover title

src/Pumukit/InstallBundleBundle/Manipulator/RoutingManipulator.php
From #1150 
this change makes more sense as 'defaults' is not being used.
When merged, also merge 2.6.x into 2.7.x and upwards to include this fix.
=> TTK-21861 InstallBundle: Removed extra unused 'defaults' parameter

src/Pumukit/SchemaBundle/Services/FactoryService.php
* The flush flag needs to be passed to other create functions to prevent flushing the mmobj
* The dispatch flag needs to be passed for the same reasons (doCreate should not dispatch events)
=> TTK-21864 SchemaBundle: Fixed doCreateMultimediaObject flush and dispatch
