src/Pumukit/OpencastBundle/Controller/MediaPackageController.php
The record date for opencast recordings was set to now()
=> add the recording start date as recordDate

src/Pumukit/SchemaBundle/Services/FactoryService.php, src/Pumukit/SchemaBundle/Services/MultimediaObjectPicService.php, src/Pumukit/SchemaBundle/Services/PersonService.php, src/Pumukit/SchemaBundle/Services/TagService.php
Optimizing functions from schema bundle.
=> Dev fix geantscript

src/Pumukit/NewAdminBundle/Controller/TrackController.php, src/Pumukit/NewAdminBundle/Resources/views/Track/info.html.twig
* Fixed url on iframe.
* Fixed url to video with track.
* Fixed url to series.
* Deleted extra 'embed' label.
=> #8703 Track info: Fix iframe content and remove 'embed' label.

src/Pumukit/WebTVBundle/Controller/IndexController.php, src/Pumukit/WebTVBundle/Resources/views/Index/loginbox.html.twig, src/Pumukit/WebTVBundle/Resources/views/Layout/baseheader.html.twig, src/Pumukit/WebTVBundle/Resources/views/Layout/mobile_header.html.twig
Added login button to log from the portal and a button to access the back-office directly
=> Feature 9286 loginbutton

src/Pumukit/PaellaPlayerBundle/Controller/PaellaRepositoryController.php, src/Pumukit/PaellaPlayerBundle/Resources/public/assets/paella_start.js, src/Pumukit/VideoEditorBundle/Resources/public/assets/paella_start.js
Added the ability to see opencast frames using the paella plugins.
=> Bugfix 9472 opencast slides

doc/updateModel_2.1_to_2.2.php, src/Pumukit/SchemaBundle/Command/PumukitInitRepoCommand.php
This fixes #75.
Instead of just adding the PUDEUNI tag, I edited the 'init:repo' command to work without the '--force' command, then called the `pumukit:init:repo tag` command from the updateModel command.
Code review.
Note: Feel free to remove the bugfix branch once it is merged
=> Bugfix 75 no pudeuni

src/Pumukit/NewAdminBundle/Controller/MultimediaObjectController.php, src/Pumukit/WorkflowBundle/EventListener/JobGeneratorListener.php
The LegacyController bugfix can be merged to 2.2.x and master
=> Update master with 2.1.x LegacyController bugfix

src/Pumukit/NewAdminBundle/Controller/MultimediaObjectController.php, src/Pumukit/WorkflowBundle/EventListener/JobGeneratorListener.php
The LegacyController bugfix can be merged to 2.2.x and master. Same as #101
=> Update 2.2.x with 2.1.x LegacyController bugfix

src/Pumukit/NewAdminBundle/Resources/views/MultimediaObject/listpub.html.twig, src/Pumukit/NewAdminBundle/Resources/views/pumukit2.css.twig, src/Pumukit/SchemaBundle/Command/TagCommand.php, src/Pumukit/SchemaBundle/Resources/data/tags/publishing_decisions_i18n.csv
And add a command to easy modify the 'display' field of a Tag from the backend.
=> Disable Publishing Decisions that aren't used on WebTVBundle

doc/updateModel_2.1_to_2.2.php, src/Pumukit/NewAdminBundle/Controller/SeriesController.php, src/Pumukit/SchemaBundle/Document/MultimediaObject.php, src/Pumukit/SchemaBundle/Event/SchemaEvents.php, src/Pumukit/SchemaBundle/Event/SeriesEvent.php, src/Pumukit/SchemaBundle/EventListener/SeriesListener.php, src/Pumukit/SchemaBundle/Resources/config/services.xml, src/Pumukit/SchemaBundle/Services/FactoryService.php, src/Pumukit/SchemaBundle/Services/SeriesEventDispatcherService.php, src/Pumukit/SchemaBundle/Services/SeriesPicService.php, src/Pumukit/SchemaBundle/Services/SeriesService.php, src/Pumukit/SchemaBundle/Tests/Services/SeriesEventDispatcherServiceTest.php, src/Pumukit/SchemaBundle/Tests/Services/SeriesPicServiceTest.php, src/Pumukit/SchemaBundle/Tests/Services/SeriesServiceTest.php
This fixes the index search in Mongo.
=> Add Series Title field to MultimediaObject

src/Pumukit/NewAdminBundle/Controller/PermissionProfileController.php, src/Pumukit/NewAdminBundle/Resources/views/pumukit2.js.twig, src/Pumukit/SchemaBundle/Services/PermissionProfileService.php, src/Pumukit/SchemaBundle/Services/PermissionService.php
=> Bugfix 10125 add batch update

src/Pumukit/NewAdminBundle/Controller/MultimediaObjectController.php, src/Pumukit/NewAdminBundle/Controller/SeriesController.php, src/Pumukit/NewAdminBundle/Form/Type/SeriesType.php, src/Pumukit/NewAdminBundle/Resources/views/Series/updatemeta.html.twig, src/Pumukit/NewAdminBundle/Resources/views/pumukit2.css.twig
=> Feature 10298 deactivate announced tag

src/Pumukit/Legacy/WebTVBundle/Resources/translations/messages.es.xlf, src/Pumukit/Legacy/WebTVBundle/Resources/translations/messages.gl.xlf, src/Pumukit/NewAdminBundle/EventListener/FilterListener.php, src/Pumukit/PodcastBundle/Resources/data/tags/itunesu_i18n.csv, src/Pumukit/SchemaBundle/Resources/data/tags/directriz_i18n.csv, src/Pumukit/SchemaBundle/Resources/data/tags/itunesu_i18n.csv, src/Pumukit/WebTVBundle/Resources/translations/messages.es.xlf, src/Pumukit/WebTVBundle/Resources/translations/messages.gl.xlf, src/Pumukit/WebTVBundle/Resources/views/default.css.twig
=> Fix little big details of UI

src/Pumukit/NewAdminBundle/Controller/PlaylistController.php, src/Pumukit/NewAdminBundle/Controller/PlaylistMultimediaObjectController.php, src/Pumukit/NewAdminBundle/Menu/Builder.php, src/Pumukit/NewAdminBundle/Resources/views/Playlist/index.html.twig, src/Pumukit/NewAdminBundle/Resources/views/Playlist/list.html.twig, src/Pumukit/NewAdminBundle/Resources/views/PlaylistMultimediaObject/addModal.html.twig
F-ixes bugs #142, #146, #145, #140 and #161.
=> Bugfixing qa playlists

src/Pumukit/NewAdminBundle/Controller/MultimediaObjectController.php, src/Pumukit/NewAdminBundle/Controller/SeriesController.php, src/Pumukit/NewAdminBundle/Resources/config/routes/mms.yml, src/Pumukit/NewAdminBundle/Resources/config/routes/series.yml, src/Pumukit/NewAdminBundle/Resources/views/MultimediaObject/listProperties.html.twig, src/Pumukit/NewAdminBundle/Resources/views/MultimediaObject/updatemenu.html.twig, src/Pumukit/NewAdminBundle/Resources/views/Series/listProperties.html.twig, src/Pumukit/NewAdminBundle/Resources/views/Series/updatemenu.html.twig
=> Add modal in the backoffice to show the series and mms properties

src/Pumukit/NewAdminBundle/Controller/PlaylistController.php, src/Pumukit/NewAdminBundle/Controller/PlaylistMultimediaObjectController.php, src/Pumukit/NewAdminBundle/Menu/Builder.php, src/Pumukit/NewAdminBundle/Resources/views/Collection/show.html.twig, src/Pumukit/NewAdminBundle/Resources/views/Pic/picstoaddlist.html.twig, src/Pumukit/NewAdminBundle/Resources/views/Playlist/changepub.html.twig, src/Pumukit/NewAdminBundle/Resources/views/Playlist/index.html.twig, src/Pumukit/NewAdminBundle/Resources/views/Playlist/list.html.twig, src/Pumukit/NewAdminBundle/Resources/views/Playlist/updatemeta.html.twig, src/Pumukit/NewAdminBundle/Resources/views/PlaylistMultimediaObject/addModal.html.twig, src/Pumukit/NewAdminBundle/Resources/views/PlaylistMultimediaObject/index.html.twig, src/Pumukit/NewAdminBundle/Resources/views/PlaylistMultimediaObject/list.html.twig, src/Pumukit/NewAdminBundle/Resources/views/PlaylistMultimediaObject/modal_search.html.twig, src/Pumukit/NewAdminBundle/Resources/views/PlaylistMultimediaObject/modal_url_list.html.twig, src/Pumukit/NewAdminBundle/Resources/views/Series/show.html.twig, src/Pumukit/NewAdminBundle/Services/SeriesSearchService.php, src/Pumukit/SchemaBundle/Repository/MultimediaObjectRepository.php, src/Pumukit/SchemaBundle/Services/EmbeddedBroadcastService.php
Each issue is referenced in its own commit.
=> Fixing several issues regarding the Moodle Playlists

src/Pumukit/NewAdminBundle/Resources/views/layout.html.twig, src/Pumukit/NewAdminBundle/Resources/views/naked_menu.html.twig
Fixes internal issue #11128.
Code review and merge.
=> Feature 11128 naked menu

src/Pumukit/NewAdminBundle/Controller/PlaylistController.php, src/Pumukit/NewAdminBundle/Resources/views/Playlist/listth.html.twig
=> Bugfix 150 playlist sorting

src/Pumukit/NewAdminBundle/Resources/config/services.xml, src/Pumukit/NewAdminBundle/Resources/views/PlaylistMultimediaObject/list.html.twig, src/Pumukit/NewAdminBundle/Twig/PumukitAdminExtension.php, src/Pumukit/SchemaBundle/Services/MultimediaObjectService.php
This warning is meant to give a more intuitive view of which mmobjs will actually be played on the playlist and which ones won't.
Note: Assign issue #187 for QA when this is merged.
=> #187 NewAdminBundle: Added warning for non-playable mmobjs.

src/Pumukit/NewAdminBundle/Resources/views/MultimediaObject/index.html.twig, src/Pumukit/NewAdminBundle/Resources/views/Playlist/index.html.twig, src/Pumukit/NewAdminBundle/Resources/views/PlaylistMultimediaObject/index.html.twig, src/Pumukit/NewAdminBundle/Resources/views/Series/index.html.twig, src/Pumukit/NewAdminBundle/Resources/views/naked_menu.html.twig
Added tabs for the "naked menu" to switch between series and playlists.
=> Feature 11158 menu titles

src/Pumukit/NewAdminBundle/Controller/PlaylistMultimediaObjectController.php, src/Pumukit/NewAdminBundle/Resources/config/routes/playlistmms.yml, src/Pumukit/NewAdminBundle/Resources/views/PlaylistMultimediaObject/index.html.twig, src/Pumukit/NewAdminBundle/Resources/views/PlaylistMultimediaObject/info.html.twig
* Creates an info template for the playlistmmobj view.
* Removes magic url setting from that template.
=> #197 NewAdminBundle: Removed magic url from playlistmmobj info.

src/Pumukit/NewAdminBundle/Controller/MultimediaObjectController.php, src/Pumukit/NewAdminBundle/Controller/PermissionProfileController.php, src/Pumukit/NewAdminBundle/Controller/SeriesController.php, src/Pumukit/NewAdminBundle/Resources/views/MultimediaObject/listpub.html.twig, src/Pumukit/NewAdminBundle/Resources/views/PermissionProfile/list.html.twig, src/Pumukit/NewAdminBundle/Resources/views/PermissionProfile/updatescope.html.twig, src/Pumukit/NewAdminBundle/Resources/views/Series/changepub.html.twig, src/Pumukit/NewAdminBundle/Resources/views/pumukit2.js.twig, src/Pumukit/SchemaBundle/Resources/config/services.xml, src/Pumukit/SchemaBundle/Security/Permission.php, src/Pumukit/SchemaBundle/Security/RoleHierarchy.php, src/Pumukit/SchemaBundle/Services/FactoryService.php, src/Pumukit/SchemaBundle/Services/PermissionService.php, src/Pumukit/SchemaBundle/Tests/EventListener/PermissionProfileListenerTest.php, src/Pumukit/SchemaBundle/Tests/Repository/PermissionProfileRepositoryTest.php, src/Pumukit/SchemaBundle/Tests/Services/PermissionServiceTest.php, src/Pumukit/SchemaBundle/Tests/Services/UserServiceTest.php, src/Pumukit/WebTVBundle/Resources/translations/messages.en.xlf, src/Pumukit/WebTVBundle/Resources/translations/messages.es.xlf, src/Pumukit/WebTVBundle/Resources/translations/messages.gl.xlf, src/Pumukit/WizardBundle/Controller/DefaultController.php, src/Pumukit/WizardBundle/Resources/views/Default/track.html.twig
Use case:
`As admin of the portal I don't want that teachers publish content in the main webtv channel.`
=> Using permissions to disable publications channels.

src/Pumukit/NewAdminBundle/Controller/MultimediaObjectController.php, src/Pumukit/NewAdminBundle/Controller/SeriesController.php, src/Pumukit/SchemaBundle/Security/Permission.php, src/Pumukit/SchemaBundle/Services/FactoryService.php, src/Pumukit/SchemaBundle/Services/PermissionService.php, src/Pumukit/SchemaBundle/Services/TagService.php, src/Pumukit/WizardBundle/Controller/DefaultController.php, src/Pumukit/WizardBundle/Resources/views/Default/track.html.twig
Creating new roles to activate by default a publication channel (and other refactors).
=> Dev 11173 pubch with profiles

src/Pumukit/JWPlayerBundle/Controller/PlaylistController.php
=> Using base route name

app/config/config.yml, src/Pumukit/CoreBundle/Controller/AdminController.php, src/Pumukit/CoreBundle/Controller/PersonalControler.php, src/Pumukit/CoreBundle/Controller/PersonalController.php, src/Pumukit/CoreBundle/Controller/TestBackofficeController.php, src/Pumukit/CoreBundle/Controller/TestPersonalController.php, src/Pumukit/CoreBundle/Controller/TestWebTVController.php, src/Pumukit/CoreBundle/Controller/WebTVController.php, src/Pumukit/CoreBundle/DependencyInjection/Configuration.php, src/Pumukit/CoreBundle/DependencyInjection/PumukitCoreExtension.php, src/Pumukit/CoreBundle/EventListener/FilterListener.php, src/Pumukit/CoreBundle/Filter/AdminFilter.php, src/Pumukit/CoreBundle/Filter/ChannelFilter.php, src/Pumukit/CoreBundle/Filter/PersonalFilter.php, src/Pumukit/CoreBundle/Filter/WebTVFilter.php, src/Pumukit/CoreBundle/PumukitCoreBundle.php, src/Pumukit/CoreBundle/Resources/config/routing.yml, src/Pumukit/CoreBundle/Resources/config/services.xml, src/Pumukit/JWPlayerBundle/Controller/BasePlayerController.php, src/Pumukit/NewAdminBundle/Controller/MultimediaObjectController.php, src/Pumukit/NewAdminBundle/Resources/views/MultimediaObject/modalPreview.html.twig
* Right now the filters logic is a little scattered between the NewAdminBundle and the WebTVBundle.
* Due to RM#11523, it would be beneficial to unify them on a CoreBundle.
=> RM#11523 CoreBundle: Creating PMK2 CoreBundle Filters

src/Pumukit/NewAdminBundle/Controller/MultimediaObjectController.php, src/Pumukit/NewAdminBundle/Controller/PersonController.php, src/Pumukit/NewAdminBundle/Resources/translations/messages.ca.xlf, src/Pumukit/NewAdminBundle/Resources/translations/messages.de.xlf, src/Pumukit/NewAdminBundle/Resources/translations/messages.en.xlf, src/Pumukit/NewAdminBundle/Resources/translations/messages.es.xlf, src/Pumukit/NewAdminBundle/Resources/translations/messages.eu.xlf, src/Pumukit/NewAdminBundle/Resources/translations/messages.fr.xlf, src/Pumukit/NewAdminBundle/Resources/translations/messages.gl.xlf, src/Pumukit/NewAdminBundle/Resources/translations/messages.hy.xlf, src/Pumukit/NewAdminBundle/Resources/translations/messages.it.xlf, src/Pumukit/NewAdminBundle/Resources/translations/messages.ja.xlf, src/Pumukit/NewAdminBundle/Resources/translations/messages.ka.xlf, src/Pumukit/NewAdminBundle/Resources/translations/messages.pt.xlf, src/Pumukit/NewAdminBundle/Resources/translations/messages.ru.xlf, src/Pumukit/NewAdminBundle/Resources/translations/messages.zh.xlf, src/Pumukit/NewAdminBundle/Resources/views/Series/updatebroadcast.html.twig, src/Pumukit/NewAdminBundle/Resources/views/pumukit2.js.twig, src/Pumukit/OpencastBundle/Resources/translations/messages.zh.xlf, src/Pumukit/PodcastBundle/Resources/translations/messages.zh.xlf, src/Pumukit/SchemaBundle/Document/EmbeddedBroadcast.php, src/Pumukit/SchemaBundle/Resources/config/services.xml, src/Pumukit/SchemaBundle/Services/EmbeddedBroadcastService.php, src/Pumukit/SchemaBundle/Tests/Services/EmbeddedBroadcastServiceTest.php, src/Pumukit/WebTVBundle/Resources/translations/messages.zh.xlf
Fix strings to translate in update Broadcast and delete Person.
Updated translations.
=> Bugfix 2.3.x translations

src/Pumukit/WizardBundle/Controller/DefaultController.php, src/Pumukit/WizardBundle/Resources/public/css/nav-wizard.bootstrap.css, src/Pumukit/WizardBundle/Resources/views/Default/license.html.twig, src/Pumukit/WizardBundle/Resources/views/Default/multimediaobject.html.twig, src/Pumukit/WizardBundle/Resources/views/Default/series.html.twig, src/Pumukit/WizardBundle/Resources/views/Default/steps.html.twig, src/Pumukit/WizardBundle/Resources/views/Default/track.html.twig, src/Pumukit/WizardBundle/Resources/views/Default/type.html.twig, src/Pumukit/WizardBundle/Resources/views/Simple/license.html.twig, src/Pumukit/WizardBundle/Services/LicenseService.php, src/Pumukit/WizardBundle/Tests/Services/LicenseServiceTest.php
* Original:
* Decrease wizard step separations:
* Bold step header text:
* Next buttons under the form:
* Show future steps:
* Set max width:
=> Feature 12474 wizard license rr

src/Pumukit/LDAPBundle/EventListener/AuthenticationHandler.php, src/Pumukit/LDAPBundle/Resources/config/services.xml
See https://symfony.com/doc/current/bundles/best_practices.html#main
=> Use EventListener directory name for AuthenticationHandler.php

src/Pumukit/WizardBundle/Controller/DefaultController.php, src/Pumukit/WizardBundle/DependencyInjection/Configuration.php, src/Pumukit/WizardBundle/DependencyInjection/PumukitWizardExtension.php, src/Pumukit/WizardBundle/Resources/public/css/nav-wizard.bootstrap.css, src/Pumukit/WizardBundle/Resources/translations/messages.en.xlf, src/Pumukit/WizardBundle/Resources/views/Default/multimediaobject.html.twig, src/Pumukit/WizardBundle/Resources/views/Default/series.html.twig, src/Pumukit/WizardBundle/Resources/views/pumukit2_wizard.js.twig
There is a new parameter mandatory_title, if set to true, the title of series and multimedia object in wizard must be filled.
=> Add mandatory title in wizard

src/Pumukit/SchemaBundle/Repository/MultimediaObjectRepository.php, src/Pumukit/SchemaBundle/Repository/SeriesRepository.php, src/Pumukit/SchemaBundle/Tests/Repository/MultimediaObjectRepositoryTest.php, src/Pumukit/SchemaBundle/Tests/Repository/SeriesRepositoryTest.php
Needs to be done with merge request in PumukitEhuWebTVBundle and merge request in PumukitEhuWizardBundle of branches with the same name.
=> Feature 13139 series broadcast

src/Pumukit/SchemaBundle/Repository/SeriesRepository.php, src/Pumukit/SchemaBundle/Tests/Repository/SeriesRepositoryTest.php
=> TTK-13139 SchemaBundle: add findByTitleWithLocale Series repo function

src/Pumukit/WebTVBundle/Resources/views/Index/loginbox.html.twig
Fix minor bugs in loginbox:
* Missing trans tags
* Wrong title in Manage my videos row
=> Feature 13216 backoffice menu

src/Pumukit/LDAPBundle/Resources/config/services.xml, src/Pumukit/LDAPBundle/Services/LDAPUserService.php
Add type to getGroup() function to be better extensible.
=> TTK-13235 LDAPBundle: fix group name

app/Resources/TwigBundle/views/Exception/error.html.twig
Follows this other pull request: #295 
After the unification of branches 2.3.x and 2.4.x in the issue #305 , the previous pull request is moved to 2.3.x branch.
=> TTK-13188 Add error template

doc/updateModel_2.2_to_2.3.php
=> hotfix on migration script, it used a lot of memory

src/Pumukit/SchemaBundle/Services/FactoryService.php, src/Pumukit/SchemaBundle/Tests/Services/FactoryServiceTest.php, src/Pumukit/WizardBundle/Controller/SimpleController.php, src/Pumukit/WizardBundle/DependencyInjection/Configuration.php, src/Pumukit/WizardBundle/DependencyInjection/PumukitWizardExtension.php, src/Pumukit/WizardBundle/Resources/config/routes/simple.yml, src/Pumukit/WizardBundle/Resources/views/Simple/embedindex.html.twig, src/Pumukit/WizardBundle/Resources/views/Simple/index.html.twig, src/Pumukit/WizardBundle/Resources/views/Simple/multimediaobjecttitle.html.twig, src/Pumukit/WizardBundle/Resources/views/Simple/seriestitle.html.twig, src/Pumukit/WizardBundle/Resources/views/pumukit2_wizard.js.twig
Add the functionality to use the simple wizard without a previous created series.
=> Feature 14114 fix series creation

src/Pumukit/WizardBundle/Controller/SimpleController.php
Make externalData more consistent.
=> TTK-14125 WizardBundle: fix simple controller with external data

src/Pumukit/WizardBundle/Controller/SimpleController.php, src/Pumukit/WizardBundle/DependencyInjection/Configuration.php, src/Pumukit/WizardBundle/DependencyInjection/PumukitWizardExtension.php
Allow to force a default master profile for multimedia objects created using the simple wizard
Used by Moodle and OpenEdx
=> TTK-14387 Allow to force a default master profile 

src/Pumukit/NewAdminBundle/Resources/translations/messages.en.xlf, src/Pumukit/NewAdminBundle/Resources/views/MultimediaObject/list.html.twig, src/Pumukit/NewAdminBundle/Resources/views/MultimediaObject/listAll.html.twig, src/Pumukit/NewAdminBundle/Resources/views/Playlist/list.html.twig, src/Pumukit/NewAdminBundle/Resources/views/PlaylistMultimediaObject/list.html.twig, src/Pumukit/NewAdminBundle/Resources/views/Series/list.html.twig
This fixes the accessibility issue of missing label on an input or select.
https://www.w3.org/TR/WCAG20-TECHS/F68.html
=> TTK-14594 Add aria-label and aria-labelledby where needed for a11y

src/Pumukit/WebTVBundle/Resources/views/Layout/baseheader.html.twig, src/Pumukit/WebTVBundle/Resources/views/Layout/mobile_header.html.twig, src/Pumukit/WebTVBundle/Resources/views/Layout/search_box.html.twig, src/Pumukit/WebTVBundle/Resources/views/Layout/stickyheader.html.twig, src/Pumukit/WebTVBundle/Resources/views/default.css.twig
This fixes F77: Failure of Success Criterion 4.1.1 due to duplicate values of type ID
https://www.w3.org/TR/WCAG20-TECHS/F77.html
=> Bugfix TTK-14614: A11Y - F77: Failure of Success Criterion 4.1.1 due to duplicate values of type ID

src/Pumukit/NewAdminBundle/Resources/views/Series/list.html.twig, src/Pumukit/NewAdminBundle/Resources/views/Series/listth.html.twig
This fixes H43: Using id and headers attributes to associate data cells with header cells in data tables.
https://www.w3.org/TR/WCAG20-TECHS/H43.html
=> TTK-14615: A11Y - H43 - Using id and headers attributes to associate data cells with header cells in data tables

src/Pumukit/NewAdminBundle/Resources/translations/messages.en.xlf, src/Pumukit/NewAdminBundle/Resources/views/Series/acordeon.html.twig
This fixes H71: Providing a description for groups of form controls using fieldset and legend elements
https://www.w3.org/TR/WCAG20-TECHS/H71.html
=> TTK-14616: A11Y - H71 - Add legend to fieldset in filter series

src/Pumukit/NewAdminBundle/Resources/translations/messages.en.xlf, src/Pumukit/NewAdminBundle/Resources/views/menu.html.twig, src/Pumukit/WebTVBundle/Resources/doc/OverrideGuide.md, src/Pumukit/WebTVBundle/Resources/translations/messages.en.xlf, src/Pumukit/WebTVBundle/Resources/views/Layout/logo.html.twig
This fixes the accessibility issue of missing description in links:
https://www.w3.org/TR/WCAG20-TECHS/H30.html
=> TTK-14605: A11Y - Fix H30 errors - Missing link descriptions

src/Pumukit/NewAdminBundle/Resources/translations/messages.en.xlf, src/Pumukit/NewAdminBundle/Resources/views/Series/list.html.twig
This fixes H37: Images must have alt attribute
https://www.w3.org/TR/WCAG20-TECHS/H37.html
=> TTK-14609: A11Y - H37 - Add alt attribute to img elements

src/Pumukit/NewAdminBundle/Resources/translations/messages.en.xlf, src/Pumukit/NewAdminBundle/Resources/views/Series/acordeon.html.twig, src/Pumukit/NewAdminBundle/Resources/views/Series/list.html.twig, src/Pumukit/NewAdminBundle/Resources/views/menu.html.twig, src/Pumukit/WebTVBundle/Resources/translations/messages.en.xlf, src/Pumukit/WebTVBundle/Resources/views/Layout/search_box.html.twig
This fixes H91 errors:
https://www.w3.org/TR/WCAG20-TECHS/H91.html
=> TTK-14610: A11Y - H91 - Using HTML form controls and links

src/Pumukit/WebTVBundle/Resources/views/default.css.twig
=> Fixed minithumbnails stretching.

.travis.yml, app/config/config.yml, app/config/doctrine_extensions.yml
https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming
=> Fix Travis.

src/Pumukit/WebTVBundle/Controller/WidgetController.php
In the webtvbundle I'm working on, the menu widget has a "next events" field. I thought adding that info to the original controller was preferrable to override the function
=> TTK-15286 Added 'live_events' to the data the menu receives.

src/Pumukit/NewAdminBundle/Resources/views/Pic/create.html.twig, src/Pumukit/NewAdminBundle/Resources/views/Track/create.html.twig, src/Pumukit/WizardBundle/Resources/views/Default/track.html.twig
Supported by IE 11 and not by Edge
https://caniuse.com/#feat=input-file-accept
=> TTK-15412 Using accept attribute for file input

src/Pumukit/WebTVBundle/Resources/public/js/announces_ajax.js
Infinite scrolling doesn't work properly on mobile devices. This fixes internal issue TTK-15309
=> Infinite scrolling on mobile devices

src/Pumukit/NewAdminBundle/Controller/LiveController.php
Avoid page changing when a live channel is deleted or updated.
=> TTK-15522 fix bug on Live Channels pager when changes page (review)

src/Pumukit/LiveBundle/Controller/DefaultController.php, src/Pumukit/LiveBundle/Resources/views/Advance/liveplayer.html.twig, src/Pumukit/NewAdminBundle/Controller/EventsController.php, src/Pumukit/NewAdminBundle/Controller/LiveController.php, src/Pumukit/NewAdminBundle/Controller/MultimediaObjectController.php, src/Pumukit/NewAdminBundle/Form/Type/EventsType.php, src/Pumukit/NewAdminBundle/Resources/views/LiveEvent/index.html.twig, src/Pumukit/NewAdminBundle/Resources/views/LiveEvent/list.html.twig, src/Pumukit/NewAdminBundle/Resources/views/LiveEvent/sessionlist.html.twig, src/Pumukit/NewAdminBundle/Resources/views/LiveEvent/updatemenu.html.twig, src/Pumukit/NewAdminBundle/Resources/views/LiveEvent/updatesessionmodal.html.twig, src/Pumukit/NewAdminBundle/Resources/views/MultimediaObject/listExternalPlayer.html.twig, src/Pumukit/NewAdminBundle/Resources/views/MultimediaObject/listpub.html.twig, src/Pumukit/SchemaBundle/Repository/MultimediaObjectRepository.php, src/Pumukit/SchemaBundle/Services/EmbeddedBroadcastService.php, src/Pumukit/WebTVBundle/Controller/EventController.php, src/Pumukit/WebTVBundle/Controller/WidgetController.php, src/Pumukit/WebTVBundle/Resources/views/Event/index.html.twig, src/Pumukit/WebTVBundle/Resources/views/Event/info.html.twig, src/Pumukit/WebTVBundle/Resources/views/Event/multimediaobject.html.twig, src/Pumukit/WebTVBundle/Resources/views/Widget/menu.html.twig
=> Feature 15135 new live events

src/Pumukit/SchemaBundle/Command/PumukitSyncRepositoryCommand.php
$ time php app/console  pumukit:sync:repository --env=prod
real0m16.164s
user0m3.511s
sys0m0.592s
$ time php app/console  pumukit:sync:repository --env=prod
real0m1.915s
user0m1.605s
sys0m0.219s
=> Take advantage of mongo aggregation framework (16s to 2s)

src/Pumukit/NewAdminBundle/Controller/PersonController.php, src/Pumukit/NewAdminBundle/Resources/views/Person/list.html.twig
=> Hotfix 15017 person ux

src/Pumukit/NewAdminBundle/Resources/views/pumukit2.js.twig
See https://github.com/campusdomar/PuMuKIT2/commit/3c661f4e
=> TTK-15132 fix JS

src/Pumukit/NewAdminBundle/Resources/views/SeriesStyle/list.html.twig, src/Pumukit/SchemaBundle/Tests/Document/MultimediaObjectTest.php, src/Pumukit/SchemaBundle/Tests/EventListener/MultimediaObjectListenerTest.php, src/Pumukit/SchemaBundle/Tests/Services/PicServiceTest.php, src/Pumukit/WebTVBundle/Resources/views/Search/filtersseries.html.twig, src/Pumukit/WorkflowBundle/Tests/EventListener/JobGeneratorListenerTest.php
Fixes errors in Travis:
- console.log() removal
- phpunit tests
- pa11y tests
=> Hotfix 15818 travis

app/config/encoder.yml, src/Pumukit/EncoderBundle/DependencyInjection/Configuration.php, src/Pumukit/EncoderBundle/DependencyInjection/PumukitEncoderExtension.php, src/Pumukit/EncoderBundle/Executor/LocalExecutor.php, src/Pumukit/EncoderBundle/Resources/config/services.xml, src/Pumukit/EncoderBundle/Services/JobService.php, src/Pumukit/EncoderBundle/Services/ProfileService.php, src/Pumukit/EncoderBundle/Tests/Funcional/FuncionalTest.php, src/Pumukit/EncoderBundle/Tests/Services/JobServiceTest.php, src/Pumukit/EncoderBundle/Tests/Services/ProfileServiceTest.php, src/Pumukit/WorkflowBundle/EventListener/JobGeneratorListener.php, src/Pumukit/WorkflowBundle/Tests/EventListener/PicExtractorListenerTest.php
Bug:
* Tracks encoded with unwanted profiles
Changes:
* Added new paramater ```target_default_profiles``` in app/config/encoder.yml
* Now profiles are chosen based on the target(s) of the multimediaobject and the target(s) of the available profiles.
=> TTK-15237 Added default encoding profiles for imported videos

src/Pumukit/WorkflowBundle/EventListener/JobGeneratorListener.php
http://phpsw.uk/talks/extremely-defensive-php
https://www.youtube.com/watch?v=8d2AtAGJPno
=> Using extreme defensive PHP

src/Pumukit/NewAdminBundle/Resources/translations/messages.es.xlf
In media argot Producer EN = Realizador ES en argot multimedia
https://github.com/campusdomar/PuMuKIT2/blob/master/src/Pumukit/SchemaBundle/Resources/data/roles/roles_i18n.csv#L4
=> TTK-15229 fix i18n

src/Pumukit/JWPlayerBundle/Resources/views/JWPlayer/player_opencast.html.twig, src/Pumukit/LiveBundle/Resources/views/Advance/liveplayer.html.twig, src/Pumukit/WebTVBundle/Resources/views/Event/miniMultimediaObjects.html.twig, src/Pumukit/WebTVBundle/Resources/views/Event/share.html.twig
=> Feature 16052 a11y

src/Pumukit/LiveBundle/Resources/views/Advance/liveplayer.html.twig, src/Pumukit/NewAdminBundle/Form/Type/EventsType.php, src/Pumukit/NewAdminBundle/Resources/translations/messages.ca.xlf, src/Pumukit/NewAdminBundle/Resources/translations/messages.de.xlf, src/Pumukit/NewAdminBundle/Resources/translations/messages.en.xlf, src/Pumukit/NewAdminBundle/Resources/translations/messages.es.xlf, src/Pumukit/NewAdminBundle/Resources/translations/messages.eu.xlf, src/Pumukit/NewAdminBundle/Resources/translations/messages.fr.xlf, src/Pumukit/NewAdminBundle/Resources/translations/messages.gl.xlf, src/Pumukit/NewAdminBundle/Resources/translations/messages.hy.xlf, src/Pumukit/NewAdminBundle/Resources/translations/messages.it.xlf, src/Pumukit/NewAdminBundle/Resources/translations/messages.ja.xlf, src/Pumukit/NewAdminBundle/Resources/translations/messages.ka.xlf, src/Pumukit/NewAdminBundle/Resources/translations/messages.pt.xlf, src/Pumukit/NewAdminBundle/Resources/translations/messages.ru.xlf, src/Pumukit/NewAdminBundle/Resources/translations/messages.zh.xlf, src/Pumukit/NewAdminBundle/Resources/views/LiveEvent/updateevent.html.twig, src/Pumukit/SchemaBundle/Document/EmbeddedEvent.php, src/Pumukit/SchemaBundle/Tests/Document/EmbeddedEventTest.php
The display messages of past or future event are now configurable in each event.
=> Feature 16829 events configurable messages

src/Pumukit/NewAdminBundle/Controller/PersonController.php, src/Pumukit/SchemaBundle/Services/PersonService.php
Wating for Mongo 3.4 and https://docs.mongodb.com/manual/reference/collation/
=> TTK-16913 Using Regex for a pseudo-collation

src/Pumukit/EncoderBundle/Services/JobService.php
Defensive programming.
PD: https://twitter.com/ultreia_es/status/925288338797617152
=> Hotfix Add FS operations inside try/catch

doc/updateModel_2.3_to_2.4.php, src/Pumukit/NewAdminBundle/Services/MultimediaObjectSearchService.php, src/Pumukit/NewAdminBundle/Services/SeriesSearchService.php, src/Pumukit/SchemaBundle/Document/MultimediaObject.php, src/Pumukit/SchemaBundle/Document/Series.php, src/Pumukit/SchemaBundle/EventListener/LocaleListener.php, src/Pumukit/SchemaBundle/Repository/MultimediaObjectRepository.php, src/Pumukit/SchemaBundle/Resources/config/services.xml, src/Pumukit/SchemaBundle/Utils/Mongo/TextIndexUtils.php, src/Pumukit/WebTVBundle/Controller/SearchController.php
Note to @mreyk `updateModel_2.3_to_2.4.php` has been updated.
=> Hotfix 17154 mongo text index language

src/Pumukit/NewAdminBundle/Resources/views/Pic/generate.html.twig
Show the size and add advanced option and configurations.
=> TTK-17788 Use jpeg, no png.

src/Pumukit/NewAdminBundle/Resources/views/MultimediaObject/editor.html.twig
Changed datalist to select
Updated layouts names
Deleted save button, save changes on select onchange event
=> TTK-17604 Delete Save button and unused layouts

src/Pumukit/NewAdminBundle/Controller/MultimediaObjectController.php
Show http://atlantic18.github.io/DoctrineExtensions/doc/sortable.html to know why -1.
=> TTK-18055 set rank value to last

src/Pumukit/WebTVBundle/Resources/views/Layout/base.html.twig
Not listed in https://github.com/joshbuchea/HEAD#meta
See https://webmasters.stackexchange.com/questions/71876/does-a-meta-title-tag-help-rankings-when-used-in-addition-to-a-title-tag
=> TTK-19068 Delete meta.title from header

app/SymfonyRequirements.php, composer.json, composer.lock
Fix: The lock file is not up to date with the latest changes in composer.json
See: https://insight.sensiolabs.com/projects/2d795933-1d37-4624-bfb7-98acdffd4e0e/analyses/4865?status=violations#669140742
=> TTK-19189 Update composer.lock with last composer.json

src/Pumukit/BasePlayerBundle/Controller/TrackFileController.php, src/Pumukit/BasePlayerBundle/Resources/config/services.xml, src/Pumukit/BasePlayerBundle/Services/TrackUrlService.php, src/Pumukit/BasePlayerBundle/Twig/BasePlayerExtension.php, src/Pumukit/NewAdminBundle/Resources/views/Pic/generate.html.twig
Fix:
Uncaught DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
at take_pic (eval at <anonymous> (https://pretv.ujaen.es/bundles/pumukitnewadmin/js/jquery-1.10.2.min.js:2:4994), <anonymous>:86:39)
at HTMLButtonElement.eval (eval at <anonymous> (https://pretv.ujaen.es/bundles/pumukitnewadmin/js/jquery-1.10.2.min.js:2:4994), <anonymous>:57:27)
take_pic @ VM216:86
(anonymous) @ VM216:57
=> TTK-19454 Fix pic generator with chrome 70

src/Pumukit/SchemaBundle/Document/MultimediaObject.php, src/Pumukit/WebTVBundle/Resources/views/Misc/multimediaobject.html.twig, src/Pumukit/WebTVBundle/Resources/views/MultimediaObject/info.html.twig
db.Series.find({'hide': true}).forEach(function(s) {
var seriesID = s._id;
db.MultimediaObject.find({'series': s._id}).forEach(function(m) {
m.seriesTitle = {};
db.MultimediaObject.save(m);
});
});
=> TTK-20532 fix performance accessing series title

src/Pumukit/InstallBundleBundle/Command/PumukitInstallBundleCommand.php, src/Pumukit/InstallBundleBundle/Manipulator/RoutingManipulator.php
These options should help when installing a bundle with a more specific routing configuration
=> InstallBundle: Added prefix/type options

src/Pumukit/NewAdminBundle/Controller/MultimediaObjectController.php, src/Pumukit/NewAdminBundle/Controller/SeriesController.php
=> TTK-21279 Check non-object

src/Pumukit/SchemaBundle/Services/EmbeddedEventSessionService.php
```php
strtotime(date('Y-m-d H:i:s', mktime(00, 00, 00, date('m'), date('d'), date('Y')))) === mktime(00, 00, 00, date('m'), date('d'), date('Y'));
strtotime(date('Y-m-d H:i:s')) == time();
```
=> TTK-21246 Delete not necessary transformations

src/Pumukit/OpencastBundle/Services/ClientService.php
After OC 6 the endpoint changes slightly. Added support for OC > 6.
=> Bugfix 21303 opencast 6 mp deletion

src/Pumukit/OpencastBundle/Command/OpencastStopWorkflowCommand.php
Apparently, when there is only one retracted mp, Opencast doesn't send an array of 1, which breaks the foreach logic.
*Note:* Also, I inverted the if statement (< 2.0.0 instead of >= 2.0.0)
=> TTK-21303 OpencastBundle: Fixed worflowStop not deleting mps

composer.lock
Should we merge this on 2.6.x as well?
=> TTK-20182 composer: Updated composer lock based on composer.json

src/Pumukit/CoreBundle/Services/FilterService.php, src/Pumukit/JWPlayerBundle/Controller/BasePlayerController.php, src/Pumukit/NewAdminBundle/Controller/EventsController.php, src/Pumukit/NewAdminBundle/Controller/MultimediaObjectController.php, src/Pumukit/NewAdminBundle/Controller/SeriesController.php, src/Pumukit/NewAdminBundle/Controller/UNESCOController.php, src/Pumukit/NewAdminBundle/Form/Type/MultimediaObjectPubType.php, src/Pumukit/NewAdminBundle/Twig/PumukitAdminExtension.php, src/Pumukit/SchemaBundle/Document/MultimediaObject.php, src/Pumukit/SchemaBundle/Services/FactoryService.php, src/Pumukit/SchemaBundle/Services/MultimediaObjectService.php, src/Pumukit/SchemaBundle/Tests/Document/BroadcastTest.php, src/Pumukit/SchemaBundle/Tests/Repository/MultimediaObjectRepositoryTest.php, src/Pumukit/SchemaBundle/Tests/Services/FactoryServiceTest.php, src/Pumukit/SchemaBundle/Tests/Services/MultimediaObjectServiceTest.php, src/Pumukit/SchemaBundle/Tests/Services/SeriesServiceTest.php, src/Pumukit/WebTVBundle/Controller/LegacyController.php, src/Pumukit/WebTVBundle/Controller/MultimediaObjectController.php
use MultimediaObject::STATUS_BLOCKED instead of MultimediaObject::STATUS_BLOQ
use MultimediaObject::STATUS_HIDDEN instead of MultimediaObject::STATUS_HIDE
=> Feature 21438 refactor video status ii

src/Pumukit/OpencastBundle/Services/ClientService.php, src/Pumukit/OpencastBundle/Services/OpencastImportService.php
* Calling the asset url directly (the assumption is that it should not change)
* Checking the mp for the asset url instead of doing a second request for attachments
In my tests, we haven't found the galicaster-properties on that list, but it could change on production
* Calling either function on importFromMediaPackage() depending on whether we found an url or not
=> TTK-21754 OpencastBundle: Changes to galicaster-properties logic

doc/docker/pumukit/Dockerfile
Download and install pumukit to get the composer cache and improve build times
=> Improve docker build times

src/Pumukit/WebTVBundle/Controller/ChannelController.php, src/Pumukit/WebTVBundle/Resources/config/services.xml, src/Pumukit/WebTVBundle/Services/ChannelService.php, src/Pumukit/WebTVBundle/Services/SearchService.php
Separated logic functions unto a service
=> TTK-19189 WebTVBundle: Refactored ChannelController

src/Pumukit/OpencastBundle/Services/OpencastImportService.php
'is_array' can't be used here, since a single track is also an 'array'. We instead check for the property 'id'
* Also, refactored the pic + attachment + genSbs for loops to simplify things
=> TTK-21958 OpencastBundle: Fixed issue with 'is_array' when importing mps

src/Pumukit/OpencastBundle/Resources/views/MultimediaObject/index.html.twig
* Fixes this:
**NOTE:** Check changes with w=1
=> TTK-22006 OpencastBundle: Fixed unaligned 'opencast track' on naked mode

src/Pumukit/NewAdminBundle/Controller/MultimediaObjectController.php, src/Pumukit/NewAdminBundle/Resources/translations/messages.en.xlf, src/Pumukit/NewAdminBundle/Resources/translations/messages.es.xlf, src/Pumukit/NewAdminBundle/Resources/views/MultimediaObject/404notfound.html.twig
This adds a customized 404 template that doesn't bring you to the webtv portal.
=> TTK-22010 NewAdminBundle: Added 404 for mm shortener url

src/Pumukit/EncoderBundle/Document/CpuStatus.php, src/Pumukit/EncoderBundle/Document/Job.php, src/Pumukit/EncoderBundle/Services/PicExtractorService.php, src/Pumukit/EncoderBundle/Services/PicService.php, src/Pumukit/NewAdminBundle/Controller/MultimediaObjectController.php, src/Pumukit/NewAdminBundle/Menu/Builder.php, src/Pumukit/NewAdminBundle/Menu/ItemsList.php, src/Pumukit/NewAdminBundle/Services/MultimediaObjectSearchService.php, src/Pumukit/NotificationBundle/Services/SenderService.php, src/Pumukit/SchemaBundle/Document/EmbeddedEvent.php, src/Pumukit/SchemaBundle/Document/EmbeddedTag.php, src/Pumukit/SchemaBundle/Document/Group.php, src/Pumukit/SchemaBundle/Document/MultimediaObject.php, src/Pumukit/SchemaBundle/Repository/SeriesRepository.php, src/Pumukit/StatsBundle/Document/Traits/Properties.php, src/Pumukit/StatsBundle/Document/ViewsAggregation.php, src/Pumukit/StatsBundle/Document/ViewsLog.php, src/Pumukit/WebTVBundle/Controller/DefaultController.php, src/Pumukit/WebTVBundle/Twig/PumukitExtension.php
This PR closes https://github.com/campusdomar/PuMuKIT/pull/1234
=> [phpstan] Use level 3 of phpstan

src/Pumukit/EncoderBundle/Services/DynamicPicExtractorService.php, src/Pumukit/SchemaBundle/Command/PumukitInitRepoCommand.php, src/Pumukit/WorkflowBundle/EventListener/PicExtractorListener.php, src/Pumukit/WorkflowBundle/Resources/config/services.xml, src/Pumukit/WorkflowBundle/Tests/EventListener/PicExtractorListenerTest.php
https://github.com/campusdomar/PuMuKIT/issues/863
=> [Insight] Replace absolute path constant __DIR__

src/Pumukit/SchemaBundle/Resources/data/tags/publishing_decisions_i18n.csv
PUDEWALL allows to use the wall web portal block
=> Add new tag by default on PuMuKIT
